version: '2'

services:
    wordpress:
        build: ./application
        ports:
            - "8000:80"
        restart: always
        environment:
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ~/workspace/feedterwp:/var/www/html
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    mysql:
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: wordpress
volumes:
    db_data: